modLoader = "javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/bigwater/icon.png"

authors="Tec, Vercte"

description='''
Larger-scale fluid textures
'''

[[mixins]]
config="bigwater.extra.mixins.json"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"